UnversityManagementSystem/Models/AssignCourse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace UnversityManagementSystem.Models
{
    public class AssignCourse
    {
        public int AssignCourseId { set; get; }
        public int DepartmentId { get; set; }
        [ForeignKey("DepartmentId")]
        public virtual Department d { get; set; }
        public int TeacherId { set; get; }
        public virtual Teacher Teacher { get; set; }
        [DefaultValue(0.0)]
        public virtual double TakenCredit { set; get; }
        [DefaultValue(0.0)]
        public virtual double RemainingCredit { set; get; }
        public int CourseId { set; get; }
        public virtual Course Course { get; set; }
    }
}

UnversityManagementSystem/Controllers/AssignCourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UnversityManagementSystem.Models;

namespace UnversityManagementSystem.Controllers
{
    public class AssignCourseController : Controller
    {
        private ProjectDb db = new ProjectDb();

        public ActionResult ViewCourseStatus()
        {
            ViewBag.departments = db.Departments.ToList();
            return View();
        }

        public ActionResult Save()
        {
            ViewBag.departments = db.Departments.ToList();
            return View();
        }

        public JsonResult GetTeachersByDeptId(int deptId)
        {
            var teachers = db.Teachers.Where(t => t.DepartmentId == deptId).ToList();
            return Json(teachers, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeachersById(int teacherId)
        {
            //var teachers = db.Teachers.Where(t => t.TeacherId == teacherId).ToList();
            Teacher aTeacher = db.Teachers.FirstOrDefault(s => s.TeacherId == teacherId);
            return Json(aTeacher, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseById(int courseId)
        {
            Course course = db.Courses.FirstOrDefault(s => s.CourseId == courseId);
            return Json(course, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveAssignCourse(AssignCourse assignCourse)
        {
            var asignCoursesList = db.AssignCourses.Where(t => t.CourseId == assignCourse.CourseId && t.Course.Status==true).ToList();
            if (asignCoursesList.Count > 0)
            {
                //course already assigned
                return Json(false);
            }
            else
            {
                db.AssignCourses.Add(assignCourse);

                db.SaveChanges();


                var teacher = db.Teachers.FirstOrDefault(t => t.TeacherId == assignCourse.TeacherId);
                if (teacher != null)
                {
                    teacher.RemainingCredit = assignCourse.RemainingCredit;
                    
                    db.Teachers.AddOrUpdate(teacher);
                    db.SaveChanges();
                    var course = db.Courses.FirstOrDefault(t => t.CourseId == assignCourse.CourseId);
                    if (course != null)
                    {
                        course.Status = true;
                        course.AssignTo = teacher.TeacherName;
                        db.Courses.AddOrUpdate(course);
                        db.SaveChanges();
                        return Json(true);
                    }
                    else
                    {
                        return Json(false);
                    }
                }
                return Json(false);
            }
        }

        public ActionResult CourseInfo(int deptId)
        {
            var courses = db.Courses.Where(t => t.DepartmentId == deptId).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
    }
}

UnversityManagementSystem/Views/AssignCourse/Save.cshtml
@model UnversityManagementSystem.Models.RoomAllocation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Course Assign to Teacher </h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">

        <div class="col-md-10" style="margin-bottom: 5px;">
            <label style="width: 150px;text-align: right;padding-right: 5px;font-size: 16px;"> Department</label>
            <select name="DepartmentId" id="DepartmentId" style="width: 200px;padding: 2px 4px; height: 25px; font-size: 14px;">
                <option value=0></option>
                @foreach (var department in ViewBag.departments)
                {
                    <option value="@department.DepartmentId">@department.DeptCode</option>
                }

            </select><label id="DeptErrorLabel" style="color: red;"></label>
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-10" style="margin-bottom: 5px;">
                <label style="width: 150px;text-align: right;padding-right: 5px;font-size: 16px;">Teacher</label>
                <select name="TeacherId" id="TeacherId" style="width: 200px; padding: 2px 4px; height: 25px; font-size: 14px;">
                    <option value=0></option>

                </select><label id="TeacherErrorLabel" style="color: red;"></label>
            </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-10" style="margin-bottom: 5px;">
            <label style="width: 150px;text-align: right;padding-right: 5px;font-size: 16px;">Credit to be taken</label>
            <input id="tCredit" type="text" style="width: 200px; padding: 2px 4px; height: 25px; font-size: 14px;" readonly="" />
        </div>
    </div>
    
     <div class="form-group">
         <div class="col-md-10" style="margin-bottom: 5px;">
             <label style="width: 150px;text-align: right;padding-right: 5px;font-size: 16px;">Remaining credit</label>
             <input id="rCredit" type="text" style="width: 200px; padding: 2px 4px; height: 25px; font-size: 14px;" readonly="" />
         </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-10" style="margin-bottom: 5px;">
            <label style="width: 150px;text-align: right;padding-right: 5px;font-size: 16px;">Course Code</label>
            <select name="CourseId" id="CourseId" style="width: 200px; padding: 2px 4px; height: 25px; font-size: 14px;">
                <option value=0></option>

            </select><label id="CourseErrorLabel" style="color: red;"></label>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-10" style="margin-bottom: 5px;">
            <label style="width: 150px;text-align: right;padding-right: 5px;font-size: 16px;">Course Name</label>
            <input id="cName" type="text" style="width: 200px; padding: 2px 4px; height: 25px; font-size: 14px;" readonly="" />
        </div>
    </div>
    
     <div class="form-group">
         <div class="col-md-10" style="margin-bottom: 5px;">
             <label style="width: 150px;text-align: right;padding-right: 5px;font-size: 16px;">Credit</label>
             <input id="cCredit" type="text" style="width: 200px; padding: 2px 4px; height: 25px; font-size: 14px;" readonly="" />
         </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-10">
            <p>
                <label style="width: 280px;text-align: right;padding-right: 5px;font-size: 16px;"></label>
                <input type="submit" id="Submit" value="Assign" class="btn btn-default" />
            </p>
        </div>
    </div>
}
<div style="clear: both;"></div>
<script src="~/Scripts/jquery-2.1.4.min.js"></script>

<script>
    $(document).ready(function() {

        $("#DepartmentId").change(function() {
            ResetLabel();

            //ResetErrorLabel();
            var departmentId = $("#DepartmentId").val();
            var jsnFormatData = { deptId: departmentId };
            $("#TeacherId").empty();
            $("#TeacherId").append('<option value=0></option>');
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeachersByDeptId", "AssignCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function(data) {

                    $.each(data, function(key, value) {
                        $("#TeacherId").append('<option value=' + value.TeacherId + '>' + value.TeacherName + '</option>');
                    });
                },
            });

            $("#CourseId").empty();
            $("#CourseId").append('<option value=0></option>');
            jsnFormatData = { deptId: departmentId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCoursesByDeptId", "RoomAllocation")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function(dataa) {

                    $.each(dataa, function(key1, value1) {
                        $("#CourseId").append('<option value=' + value1.CourseId + '>' + value1.CourseCode + '</option>');
                    });
                }
            });
            return false;
        });

        $("#TeacherId").change(function() {
            var teacherId = $("#TeacherId").val();
            var jsnFormatData = { teacherId: teacherId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeachersById", "AssignCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function(data) {
                    //alert(data.TakenCredit + " " + data.RemainingCredit);
                    $("#tCredit").val(data.TakenCredit);
                    $("#rCredit").val(data.RemainingCredit);
                },
            });
            if (teacherId == 0) {
                $("#rCredit").val("");
                $("#tCredit").val("");
            }
            return false;
        });

        $("#CourseId").change(function() {
            var courseId = $("#CourseId").val();
            var jsnFormatData = { courseId: courseId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseById", "AssignCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function(data) {
                    $("#cName").val(data.CourseName);
                    $("#cCredit").val(data.Credit);
                },
            });
            if (courseId == 0) {
                $("#cName").val("");
                $("#cCredit").val("");
            }
            return false;
        });

        $("#Submit").click(function() {
            var errorValue = 0;
            // ResetLabel();
            var departmentId = $("#DepartmentId").val();

            if (departmentId == 0) {
                $("#DeptErrorLabel").text("Select One Department!");
                errorValue = 1;
            }

            var teacherId = $("#TeacherId").val();

            if (teacherId == 0) {
                $("#TeacherErrorLabel").text("Select One Teacher!");
                errorValue = 1;
            }

            var courseId = $("#CourseId").val();
            if (courseId == 0) {
                $("#CourseErrorLabel").text("Select One Course!");
                errorValue = 1;
            }
            if (errorValue == 1) {
                return false;
            } else {

                var remCr = $("#rCredit").val() - $("#cCredit").val();
                var r = false;
                if (remCr < 0) {

                    r = confirm("The Teacher has alreay too many Credits. Do You assign More...");
                }
                if (r == true || remCr > 0) {
                    //////
                    var tC = $("#tCredit").val();
                    
                    var jsnFormatData = { DepartmentId: departmentId, TeacherId: teacherId, CourseId: courseId, TakenCredit: tC, RemainingCredit: remCr };
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("SaveAssignCourse", "AssignCourse")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jsnFormatData),
                        dataType: "json",
                        success: function(data) {

                            if (data == true)
                                alert("Successfully Assigned");
                            else {
                                alert("This course is already Assigned");
                            }
                            Reset();
                        },
                    });

                } 
                    return false;
                }
                
            });
            return false;
    });

        function Reset() {
            $("#rCredit").val("");
            $("#tCredit").val("");
            $("#CourseId").empty();
            $("#TeacherId").empty();
            $("#cName").val("");
            $("#cCredit").val("");
            $("#DepartmentId").prop("selectedIndex", 0);
        }

        function ResetLabel() {
            $("#DeptErrorLabel").text("");
            $("#TeacherErrorLabel").text("");
            $("#CourseErrorLabel").text("");
        }

</script>

UnversityManagementSystem/Views/AssignCourse/ViewCourseStatus.cshtml
@model UnversityManagementSystem.Models.AssignCourse

<h2>View Course Status</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.LabelFor(model => model.DepartmentId, "Department", new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @*@Html.DropDownList("DepartmentId", String.Empty)
            @Html.ValidationMessageFor(model => model.DepartmentId)*@
        <select name="DepartmentId" id="DepartmentId" style="background: #E9EAED; width: 120px; text-align: center;">
            <option value=0></option>
            @foreach (var department in ViewBag.departments)
            {
                <option value=@department.DepartmentId>@department.DeptCode</option>
            }

        </select><label id="DeptErrorLabel" style="color: red;"></label>
    </div>
    <label id="messageLabel" style="color: #FFB90F; font-weight: normal; font-size: 20px;"></label>
    <div id="UpdatePanel">

    </div>
}
<div  style="clear: ">
    
</div>
<script src="~/Scripts/jquery-2.1.4.js"></script>
<script>
    $(document).ready(function() {
        //$("#CourseTable").hide();
        $("#DepartmentId").change(function() {
            var deptId = $("#DepartmentId").val();
            $("#messageLabel").text("");
            var jsnFormatData = { deptId: deptId };

            $.ajax({
                type: "POST",
                url: '@Url.Action("CourseInfo", "AssignCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function (dataa) {
                    var tab = $('<table id="CourseTable" class="table">');
                    var thead = $('<thead style="line-height: 30px; color: #ffffff; font-weight: normal; font-size: 16px;"></thead>');
                    thead.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Course Code</th>');
                    thead.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Course Title</th>');
                    thead.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Semester</th>');
                    thead.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Assign To</th>');

                    thead.css('background-color', '#ffb90f');
                    tab.append(thead);

                    var tablerow = false;
                    $("#UpdatePanel").show();
                    $.each(dataa, function (key2, value2) {
                        var trow = $('<tr></tr>');
                        var ass2 = value2.AssignTo;
                        if (ass2 == null || ass2=="") ass2 = 'Not Assigned Yet';
                        trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value2.CourseCode + '</td>');
                        trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value2.CourseName + '</td>');
                        trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value2.Sem.SemesterName + '</td>');
                        trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + ass2 + '</td>');
                        tab.append(trow);
                        tablerow = true;
                    });

                    $("tr:odd", tab).css('background-color', '#F5F5F5');
                    $("tr:even", tab).css('background-color', '#EEEEEE');
                    $("#UpdatePanel").html(tab);
                    if (tablerow == false) {
                        $("#UpdatePanel").hide();
                        if(deptId!=0)
                        $("#messageLabel").text("No Courses are Available in this Department.");
                    }
                },
            });
            return false;
        });
    });
</script>