UnversityManagementSystem/Models/EnrollCourse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UnversityManagementSystem.Models
{
    public class EnrollCourse
    {
        public int EnrollCourseId { set; get; }
        [Required(ErrorMessage = "Pleae enter a student")]
        [Display(Name = "Student Reg. No.")]
        public string RegistrationId { set; get; }
        public virtual Student Student { set; get; }
        [Required(ErrorMessage = "Pleae enter a course")]
        [Display(Name = "Select Course")]
        public int CourseId { set; get; }
        public virtual Course Course { set; get; }
        [Display(Name = "Date")]
        [Required(ErrorMessage = "Please enter a date")]
        [DataType(DataType.Date)]
        public DateTime EnrollDate { set; get; }

        public virtual string GradeName { set; get; }
        
    }
}

UnversityManagementSystem/Controllers/EnrollCourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security.Provider;
using UnversityManagementSystem.Models;

namespace UnversityManagementSystem.Controllers
{
    public class EnrollCourseController : Controller
    {
        public ProjectDb db = new ProjectDb();

        // GET: /EnrollCourse/
        public ActionResult Index()
        {
            var enrollcourses = db.EnrollCourses.Include(e => e.Course);
            return View(enrollcourses.ToList());
        }

        // GET: /EnrollCourse/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnrollCourse enrollcourse = db.EnrollCourses.Find(id);
            if (enrollcourse == null)
            {
                return HttpNotFound();
            }
            return View(enrollcourse);
        }

        // GET: /EnrollCourse/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.StudentList = db.Students.ToList();
            return View();
        }

        // POST: /EnrollCourse/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="EnrollCourseId,RegistrationId,CourseId,EnrollDate,GradeName")] EnrollCourse enrollcourse)
        {
            if (ModelState.IsValid)
            {
                db.EnrollCourses.Add(enrollcourse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", enrollcourse.CourseId);
            return View(enrollcourse);
        }

        // GET: /EnrollCourse/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnrollCourse enrollcourse = db.EnrollCourses.Find(id);
            if (enrollcourse == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", enrollcourse.CourseId);
            return View(enrollcourse);
        }

        // POST: /EnrollCourse/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="EnrollCourseId,RegistrationId,CourseId,EnrollDate,GradeName")] EnrollCourse enrollcourse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollcourse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", enrollcourse.CourseId);
            return View(enrollcourse);
        }

        // GET: /EnrollCourse/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnrollCourse enrollcourse = db.EnrollCourses.Find(id);
            if (enrollcourse == null)
            {
                return HttpNotFound();
            }
            return View(enrollcourse);
        }

        public ActionResult SaveResult()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.StudentList = db.Students.ToList();
            ViewBag.GradeList = db.Grades.ToList();
            return View();
        }

        // POST: /EnrollCourse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EnrollCourse enrollcourse = db.EnrollCourses.Find(id);
            db.EnrollCourses.Remove(enrollcourse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ViewResult()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.StudentList = db.Students.ToList();
            return View();
        }

        public JsonResult GetStudentById(string regNo)
        {
            var student = db.Students.Where(s => s.RegistrationId == regNo).ToList();
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCoursesbyDept(int deptCode)
        {
            var courses = db.Courses.Where(c => c.DepartmentId == deptCode).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsEnrolled(string regNo, int courseId)
        {
            var enrollCourses = db.EnrollCourses.Where(s => s.RegistrationId == regNo && s.CourseId == courseId);
            int itm = enrollCourses.Count();
            if (itm==0)
            {
                return Json(false);
            }
            return Json(true);
        }

        public ActionResult EnrollCoursetoStudent(EnrollCourse enrollCourse)
        {
            var enrollCourses = db.EnrollCourses.Where(s => s.RegistrationId == enrollCourse.RegistrationId && s.CourseId == enrollCourse.CourseId).ToList();
            int itm = enrollCourses.Count();
            if (itm == 1)
            {
                var id = enrollCourses[0].EnrollCourseId;
                var date = enrollCourses[0].EnrollDate;
                enrollCourse.EnrollCourseId = id;
                enrollCourse.EnrollDate = date;
                db.EnrollCourses.AddOrUpdate(enrollCourse);
            }
            else
            {
                db.EnrollCourses.Add(enrollCourse);
            }
           
            db.SaveChanges();
            return Json(true);
        }

        public ActionResult GetCoursesbyRegNo(string regNo)
        {
            var courses = db.EnrollCourses.Where(c => c.RegistrationId == regNo).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PDFDemo()
        {
            return View();
        }
    }
}

UnversityManagementSystem/Views/EnrollCourse/Create.cshtml
@model UnversityManagementSystem.Models.EnrollCourse

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EnrollCourse</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.RegistrationId)*@
                <select name="RegistrationId" id="RegistrationId">
                    <option value=""></option>
                    @foreach (var student in ViewBag.StudentList)
                    {
                        <option value="@student.RegistrationId">@student.RegistrationId</option>
                    }

                </select>
                @Html.ValidationMessageFor(model => model.RegistrationId)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="text" name="name" id="name" readonly="" />
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Email", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="text" name="email" id="email" readonly="" />
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Department", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="text" name="department" id="department" readonly="" />
            </div>
        </div>
       
        <div class="form-group">
            @*@Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", String.Empty)
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>*@
            @Html.Label("Course", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="CourseId" id="CourseId"></select>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EnrollDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.EnrollDate)
                @Html.ValidationMessageFor(model => model.EnrollDate)*@
                <input type="date" id="EnrollDate" name="EnrollDate" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="Submit" name="Submit" value="Enroll" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-2.1.4.js"></script>
<script>
    $(document).ready(function() {
    
         $("#RegistrationId").change(function() {
             var regNo = $("#RegistrationId").val();
             var jsnFormatData = { regNo: regNo };
           
             $.ajax({
                 type: "POST",
                 url: '@Url.Action("GetStudentById","EnrollCourse")',
                 contentType: "application/json; charset=utf-8",
                 data: JSON.stringify(jsnFormatData),
                 dataType:"json",
                 success: function (data) {
                     $.each(data, function (key, value) {
                        
                         $("#name").val(value.StudentName);
                         $("#email").val(value.Email);
                         $("#department").val(value.d.DeptCode);

                         var deptCode = value.d.DepartmentId;
                         $("#CourseId").empty();
                         var jsnData = { deptCode: deptCode };
                         //alert(deptCode);
                         $.ajax({
                             type: "POST",
                             url: '@Url.Action("GetCoursesbyDept","EnrollCourse")',
                             contentType: "application/json; charset=utf-8",
                             data: JSON.stringify(jsnData),
                             dataType: "json",
                             success: function (dataa) {
                                 $.each(dataa, function (key1, value1) {
                                     //alert(value1.CourseId + " " + value1.CourseCode);
                                     $("#CourseId").append('<option value=' + value1.CourseId + '>' + value1.CourseCode + '</option>');
                                 });
                             },
                         });
                     });
                 },
             });
            
             return false;
         });
        $("#Submit").click(function () {
            var regNo = $("#RegistrationId").val();
            if (regNo == "") {
                alert("Select Your Registration No");
                return false;
            }
            var date = $("#EnrollDate").val();
            if (date == "") {
                alert("Select Date");
                return false;
            }
            var courseId = $("#CourseId").val();
            //alert(courseId);
            var jsnData = { regNo: regNo, courseId: courseId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("IsEnrolled","EnrollCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnData),
                dataType: "json",
                success: function (data) {
                    if (data == false) {
                        var jsnFormatData = { RegistrationId: regNo, CourseId: courseId, EnrollDate: date };
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("EnrollCoursetoStudent","EnrollCourse")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(jsnFormatData),
                            dataType: "json",
                            success: function (data) {
                                alert("Successfully Enrolled!");
                                $("#RegistrationId").prop("selectedIndex", 0);
                                $("#name").val("");
                                $("#email").val("");
                                $("#department").val("");
                                $("#CourseId").empty();
                                $("#EnrollDate").val('mm/dd/yyyy');
                            },
                        });
                        return false;
                    }
                    alert("This Student is already enrolled in this course");
                    return false;
                },
            });
            return false;
        });
    });
   
</script>






<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UnversityManagementSystem/Views/EnrollCourse/Delete.cshtml
@model UnversityManagementSystem.Models.EnrollCourse

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EnrollCourse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradeName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UnversityManagementSystem/Views/EnrollCourse/Details.cshtml
@model UnversityManagementSystem.Models.EnrollCourse

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>EnrollCourse</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradeName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnrollCourseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UnversityManagementSystem/Views/EnrollCourse/Edit.cshtml
@model UnversityManagementSystem.Models.EnrollCourse

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EnrollCourse</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.EnrollCourseId)

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationId)
                @Html.ValidationMessageFor(model => model.RegistrationId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", String.Empty)
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnrollDate)
                @Html.ValidationMessageFor(model => model.EnrollDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GradeName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GradeName)
                @Html.ValidationMessageFor(model => model.GradeName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UnversityManagementSystem/Views/EnrollCourse/Index.cshtml
@model IEnumerable<UnversityManagementSystem.Models.EnrollCourse>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrollDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GradeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.CourseCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EnrollDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GradeName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EnrollCourseId }) |
            @Html.ActionLink("Details", "Details", new { id=item.EnrollCourseId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EnrollCourseId })
        </td>
    </tr>
}

</table>

UnversityManagementSystem/Views/EnrollCourse/SaveResult.cshtml
@model UnversityManagementSystem.Models.EnrollCourse
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Save Student Result</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationId,"Reg No.", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.RegistrationId)*@
                <select name="RegistrationId" id="RegistrationId">
                    <option value=""></option>
                    @foreach (var student in ViewBag.StudentList)
                    {
                        <option value="@student.RegistrationId">@student.RegistrationId</option>
                    }

                </select>
                @Html.ValidationMessageFor(model => model.RegistrationId)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="text" name="name" id="name" readonly="" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="text" name="email" id="email" readonly="" />
            </div>
        </div>


        
        <div class="form-group">
            @Html.Label("Department", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="text" name="department" id="department" readonly="" />
            </div>
        </div>
        <div class="form-group">
            @*@Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CourseId", String.Empty)
                    @Html.ValidationMessageFor(model => model.CourseId)
                </div>*@
            
            @Html.Label("Course", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <select name="CourseId" id="CourseId">
                    <option value=""></option>
                </select>
               
            </div>
    
            
        </div>
        <div class="form-group">
            @Html.Label("Select Grade Letter", new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.TakenCredit, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <select name="GradeName" id="GradeName">
                    <option value=""></option>
                    @foreach (var grade in ViewBag.GradeList)
                    {
                        <option value=@grade.GradeName>@grade.GradeName</option>
                    }

                </select>
            </div>
        </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" id="Submit" name="Submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<script src="~/Scripts/jquery-2.1.4.js"></script>
<script>
    $(document).ready(function() {

         $("#RegistrationId").change(function() {
             var regNo = $("#RegistrationId").val();
             var jsnFormatData = { regNo: regNo };

             $.ajax({
                 type: "POST",
                 url: '@Url.Action("GetStudentById","EnrollCourse")',
                 contentType: "application/json; charset=utf-8",
                 data: JSON.stringify(jsnFormatData),
                 dataType:"json",
                 success: function (data) {
                     $.each(data, function (key, value) {

                         $("#name").val(value.StudentName);
                         $("#email").val(value.Email);
                         $("#department").val(value.d.DeptCode);

                         
                         $("#CourseId").empty();
                         $("#CourseId").append('<option value=' +""+ '>' +""+ '</option>');
                         var jsnData = { regNo: regNo };
                         $.ajax({
                             type: "POST",
                             url: '@Url.Action("GetCoursesbyRegNo","EnrollCourse")',
                             contentType: "application/json; charset=utf-8",
                             data: JSON.stringify(jsnData),
                             dataType: "json",
                             success: function (dataa) {
                                 $.each(dataa, function (key1, value1) {
                                     //alert(value1.CourseId + " " + value1.CourseCode);
                                     $("#CourseId").append('<option value=' + value1.CourseId + '>' + value1.Course.CourseCode + '</option>');
                                 });
                             },
                         });
                     });
                 },
             });

             return false;
         });
        $("#Submit").click(function () {
            var regNo = $("#RegistrationId").val();
            if (regNo == "") {
                alert("Select Your Registration No");
                return false;
            }

            var courseId = $("#CourseId").val();
            if (courseId == "") {
                alert("Select Course");
                return false;
            }

            var grd = $("#GradeName").val();
            if (grd == "") {
                alert("Select Grade");
                return false;
            }

            //alert(courseId);
           
            var jsnFormatData = { RegistrationId: regNo, CourseId: courseId, GradeName: grd};
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("EnrollCoursetoStudent","EnrollCourse")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(jsnFormatData),
                            dataType: "json",
                            success: function (data) {
                                alert("Result Saved Successfully!");
                                $("#RegistrationId").prop("selectedIndex", 0);
                                $("#name").val("");
                                $("#email").val("");
                                $("#department").val("");
                                $("#CourseId").empty();
                                $("#GradeName").prop("selectedIndex", 0);
                            },
                            
                        });
                        return false;  
            });
    });
</script>