UnversityManagementSystem/Models/RoomAllocation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UnversityManagementSystem.Models
{
    public class RoomAllocation
    {
        public int RoomAllocationId { get; set; }
        public int DepartmentId { get; set; }
        public virtual Department Department { get; set; }
        public int CourseId { get; set; }
        public virtual Course Course { get; set; }
        public int RoomId { get; set; }
        public virtual Room Room { get; set; }
        public int DayId { get; set; }
        public virtual Day Day { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public string Status { get; set; }
    }
}

UnversityManagementSystem/Controllers/RoomAllocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UnversityManagementSystem.Models;

namespace UnversityManagementSystem.Controllers
{
    public class RoomAllocationController : Controller
    {
        private ProjectDb db = new ProjectDb();

        // GET: /RoomAllocation/
        public ActionResult Index()
        {

            ViewBag.departments = db.Departments.ToList();
            return View();
        }

        // GET: /RoomAllocation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomAllocation roomallocation = db.RoomAllocations.Find(id);
            if (roomallocation == null)
            {
                return HttpNotFound();
            }
            return View(roomallocation);
        }

        // GET: /RoomAllocation/Create
        public ActionResult Create()
        {
            //ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            //ViewBag.DayId = new SelectList(db.Days, "DayId", "Name");
            //ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DeptCode");
            //ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name");
            ViewBag.courses = db.Courses.Where(s=>s.Status==true).ToList();
            ViewBag.departments = db.Departments.ToList();
            ViewBag.Rooms = db.Rooms.ToList();
            ViewBag.Days = db.Days.ToList();
            return View();
        }

        //// POST: /RoomAllocation/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include="RoomAllocationId,DepartmentId,CourseId,RoomId,DayId,StartTime,EndTime")] RoomAllocation roomallocation)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.RoomAllocations.Add(roomallocation);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", roomallocation.CourseId);
        //    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
        //    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DeptCode", roomallocation.DepartmentId);
        //    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
        //    return View(roomallocation);
        //}

        // GET: /RoomAllocation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomAllocation roomallocation = db.RoomAllocations.Find(id);
            if (roomallocation == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", roomallocation.CourseId);
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DeptCode", roomallocation.DepartmentId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
            return View(roomallocation);
        }

        // POST: /RoomAllocation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoomAllocationId,DepartmentId,CourseId,RoomId,DayId,StartTime,EndTime")] RoomAllocation roomallocation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomallocation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", roomallocation.CourseId);
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DeptCode", roomallocation.DepartmentId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
            return View(roomallocation);
        }

        // GET: /RoomAllocation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomAllocation roomallocation = db.RoomAllocations.Find(id);
            if (roomallocation == null)
            {
                return HttpNotFound();
            }
            return View(roomallocation);
        }

        // POST: /RoomAllocation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RoomAllocation roomallocation = db.RoomAllocations.Find(id);
            db.RoomAllocations.Remove(roomallocation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult GetCoursesByDeptId(int deptId)
        {
            var courses = db.Courses.Where(t => t.DepartmentId == deptId).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveRoomSchedule(RoomAllocation roomAllocation)
        {
            var scheduleList = db.RoomAllocations.Where(t => t.RoomId == roomAllocation.RoomId && t.DayId == roomAllocation.DayId && t.Status=="Allocated").ToList();
            if (scheduleList.Count == 0)
            {
                roomAllocation.Status = "Allocated";
                db.RoomAllocations.Add(roomAllocation);
                db.SaveChanges();
                return Json(true);
            }
            else
            {
                bool state = false;
                foreach (var allocation in scheduleList)
                {
                    if ((roomAllocation.StartTime >= allocation.StartTime && roomAllocation.StartTime < allocation.EndTime)
                         || (roomAllocation.EndTime > allocation.StartTime && roomAllocation.EndTime <= allocation.EndTime) && roomAllocation.Status=="Allocated")
                    {
                        state = true;
                    }
                }
                if (state == false)
                {
                    roomAllocation.Status = "Allocated";
                    db.RoomAllocations.Add(roomAllocation);
                    db.SaveChanges();
                    return Json(true);
                }
                else
                {
                    return Json(false);
                }
            }

        }

        public JsonResult GetClassScheduleInfo(int deptId)
        {
            var courses = db.Courses.Where(t => t.DepartmentId == deptId).ToList();
            List<ClassSchedule> classSchedules = new List<ClassSchedule>();
            foreach (var course in courses)
            {
                string schedule = "";
                int counter = 0;
                var courseSchedules = db.RoomAllocations.Where(t => t.DepartmentId == course.DepartmentId && t.CourseId == course.CourseId && t.Status=="Allocated").ToList();
                foreach (var courseSchedule in courseSchedules)
                {
                    if (counter != 0)
                    {
                        schedule += "; ";
                    }
                    schedule += "R. No : " + courseSchedule.Room.Name + ", " + courseSchedule.Day.Name.Substring(0, 3) + ", ";
                    int h, m;
                    string p = "AM";
                    int st = courseSchedule.StartTime;
                    h = st / 60;
                    m = st - (h * 60);
                    if (st >= 720)
                    {
                        h -= 12;
                        if (h == 0) h = 12;
                        p = "PM";
                    }
                    schedule += h + ":" + m.ToString("00") + " " + p + " - ";
                    int et = courseSchedule.EndTime;
                    h = et / 60;
                    m = et - (h * 60);
                    p = "AM";
                    if (et >= 720)
                    {
                        h -= 12;
                        if (h == 0) h = 12;
                        p = "PM";
                    }
                    schedule += h + ":" + m.ToString("00") + " " + p;
                    counter++;
                }
                if (schedule == "") schedule = "Not Scheduled Yet.";
                ClassSchedule classSchedule = new ClassSchedule(course.CourseCode, course.CourseName, schedule);
                classSchedules.Add(classSchedule);
            }
            return Json(classSchedules, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UnallocateRoom()
        {
            return View();
        }

        public JsonResult UnallocateAllRooms(bool name)
        {
            var roomInfo = db.RoomAllocations.Where(r => r.Status == "Allocated").ToList();

UnversityManagementSystem/Views/RoomAllocation/Create.cshtml
@model UnversityManagementSystem.Models.RoomAllocation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RoomAllocation</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("DepartmentId", String.Empty)
                @Html.ValidationMessageFor(model => model.DepartmentId)*@
                <select name="DepartmentId" id="DepartmentId">
                    <option value=0></option>
                    @foreach (var department in ViewBag.departments)
                    {
                        <option value="@department.DepartmentId">@department.DeptCode</option>
                    }

                </select><label id="DeptErrorLabel" style="color: red;"></label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("CourseId", String.Empty)
                @Html.ValidationMessageFor(model => model.CourseId)*@
                <select name="CourseId" id="CourseId">
                    <option value=0></option>
                    @*@foreach (var course in ViewBag.courses)
                    {
                        <option value="@course.CourseId">@course.CourseCode</option>
                    }*@

                </select><label id="CourseErrorLabel" style="color: red;"></label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "Room", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("RoomId", String.Empty)
                @Html.ValidationMessageFor(model => model.RoomId)*@
                
                <select name="RoomId" id="RoomId">
                    <option value=0></option>
                    @foreach (var room in ViewBag.Rooms)
                    {
                        <option value="@room.RoomId">@room.Name</option>
                    }

                </select><label id="RoomErrorLabel" style="color: red;"></label>

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayId, "Day", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("DayId", String.Empty)
                @Html.ValidationMessageFor(model => model.DayId)*@
                <select name="DayId" id="DayId">
                    <option value=0></option>
                    @foreach (var day in ViewBag.Days)
                    {
                        <option value="@day.DayId">@day.Name</option>
                    }

                </select><label id="DayErrorLabel" style="color: red;"></label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime,"From", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime)*@
                <input type="time" id="StartTime" name="StartTime" /> <label id="sTimeErrorLabel" style="color: red;"></label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, "To", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.EndTime)
                @Html.ValidationMessageFor(model => model.EndTime)*@
                <input type="time" id="EndTime" name="EndTime" /><label id="eTimeErrorLabel" style="color: red;"></label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" id="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>

  
               

}

<script src="~/Scripts/jquery-2.1.4.min.js"></script>

<script>
    $(document).ready(function() {

        $("#DepartmentId").change(function() {
            var departmentId = $("#DepartmentId").val();
            var jsnFormatData = { deptId: departmentId };
            $("#CourseId").empty();
            $("#CourseId").append('<option value=0></option>');
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCoursesByDeptId", "RoomAllocation")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function (data) {
                    
                    $.each(data, function (key1, value1) {
                        //alert(value1.CourseId + " " + value1.CourseCode);
                        $("#CourseId").append('<option value=' + value1.CourseId + '>' + value1.CourseCode + '</option>');
                    });
                }
            });
        });

        $("#Submit").click(function () {
            var errorValue = 0;
            ResetErrorLabel();
            var departmentId = $("#DepartmentId").val();
            if (departmentId == 0) {
                $("#DeptErrorLabel").text("Select One Department!");
                errorValue = 1;
               
            }

            var courseId = $("#CourseId").val();
            if (courseId == 0) {
                $("#CourseErrorLabel").text("Select One Course!");
                errorValue = 1;
            }

            var roomId = $("#RoomId").val();
            if (roomId == 0) {
                $("#RoomErrorLabel").text("Select One Room!");
                errorValue = 1;
            }
          
            var dayId = $("#DayId").val();
            if (dayId == 0) {
                $("#DayErrorLabel").text("Select One Day!");
                errorValue = 1;
            }
            
            var time = $("#StartTime").val();

            if (time == "") {
                //alert("start time required");
                $("#sTimeErrorLabel").text("Start time is Required!");
                errorValue = 1;
            }
           
            var hour = parseInt(time.substr(0, 2));
            var minute = parseInt(time.substr(3, 5));
            var sTime = hour * 60 + minute;
            //alert(sTime);

            time = $("#EndTime").val();
            if (time == "") {
                //alert("start time required");
                $("#eTimeErrorLabel").text("End time is Required!");
                errorValue = 1;
            }

            hour = parseInt(time.substr(0, 2));
            minute = parseInt(time.substr(3, 5));
            var eTime = hour * 60 + minute;
            //alert(eTime);
            
            if (errorValue == 1) {
                return false;
            }

            if (sTime == eTime) {
                alert("A Class Can Not be done in Zero minute");
                return false;
            }

            var jsnFormatData = { DepartmentId: departmentId, CourseId: courseId, RoomId: roomId, DayId: dayId, StartTime: sTime, EndTime: eTime};

            $.ajax({
                type: "POST",
                url: '@Url.Action("SaveRoomSchedule", "RoomAllocation")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function (data) {
                    if (data == true) {
                        alert("Class Schedule Saved Successfully!");
                        $("#DepartmentId").prop("selectedIndex", 0);
                        $("#CourseId").prop("selectedIndex", 0);
                        $("#RoomId").prop("selectedIndex", 0);
                        $("#DayId").prop("selectedIndex", 0);
                        $("#StartTime").val('mm/dd/yyyy');
                        $("#EndTime").val('mm/dd/yyyy');
                        return false;
                    } else {
                        alert("Overlap Problem, Try to Change Time or Day.");
                        return false;
                    }
                }
            });

            return false;
        });
            
    });
       
 

    function ResetErrorLabel() {
        $("#DeptErrorLabel").text("");
        $("#CourseErrorLabel").text("");
        $("#RoomErrorLabel").text("");
        $("#DayErrorLabel").text("");
        $("#sTimeErrorLabel").text("");
        $("#eTimeErrorLabel").text("");
    }

</script>

UnversityManagementSystem/Views/RoomAllocation/Delete.cshtml
@model UnversityManagementSystem.Models.RoomAllocation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RoomAllocation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DeptCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DeptCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UnversityManagementSystem/Views/RoomAllocation/Details.cshtml
@model UnversityManagementSystem.Models.RoomAllocation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>RoomAllocation</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DeptCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DeptCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RoomAllocationId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UnversityManagementSystem/Views/RoomAllocation/Edit.cshtml
@model UnversityManagementSystem.Models.RoomAllocation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RoomAllocation</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.RoomAllocationId)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", String.Empty)
                @Html.ValidationMessageFor(model => model.DepartmentId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", String.Empty)
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "RoomId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", String.Empty)
                @Html.ValidationMessageFor(model => model.RoomId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayId, "DayId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DayId", String.Empty)
                @Html.ValidationMessageFor(model => model.DayId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime)
                @Html.ValidationMessageFor(model => model.EndTime)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UnversityManagementSystem/Views/RoomAllocation/Index.cshtml
@model UnversityManagementSystem.Models.RoomAllocation

<h2>Class Schedule and Room Allocation</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

        @Html.LabelFor(model => model.DepartmentId, "Department", new { @class = "control-label col-md-2" })
<div class="col-md-10">
    @*@Html.DropDownList("DepartmentId", String.Empty)
                @Html.ValidationMessageFor(model => model.DepartmentId)*@
    <select name="DepartmentId" id="DepartmentId" style="background: #E9EAED; width: 120px; text-align: center;">
        <option value=0></option>
                @foreach (var department in ViewBag.departments)
        {
            <option value= @department.DepartmentId >@department.DeptCode</option>
        }
    
    </select><label id="DeptErrorLabel" style="color: red;"></label>
</div>
    <label id="messageLabel" style="color: #FFB90F; font-weight: normal; font-size: 20px;"></label>
    <div id="UpdatePanel">
 
    </div>
}

<script src="~/Scripts/jquery-2.1.4.js"></script>
<script>
    $(document).ready(function() {
        //$("#CourseTable").hide();
        $("#DepartmentId").change(function() {
            var deptId = $("#DepartmentId").val();
            $("#messageLabel").text("");
            var jsnFormatData = { deptId: deptId };

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetClassScheduleInfo", "RoomAllocation")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsnFormatData),
                dataType: "json",
                success: function (dataa) {
                    var tab = $('<table id="CourseTable" class="table">');
                    var thead = $('<thead style="line-height: 30px; color: #ffffff; font-weight: normal; font-size: 16px;"></thead>');
                    thead.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Course Code</th>');
                    thead.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Name</th>');
                    thead.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Schedule Info</th>');
                   
                    thead.css('background-color', '#ffb90f');
                    tab.append(thead);

                    var tablerow = false;
                    $("#UpdatePanel").show();
                    $.each(dataa, function (key2, value2) {
                        var trow = $('<tr></tr>');
                        var gread = value2.GradeName;
                        if (gread == null) gread = 'Not Graded Yet';
                        trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value2.CourseCode + '</td>');
                        trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value2.CourseName + '</td>');
                        trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value2.Schedule + '</td>');
                        tab.append(trow);
                        tablerow = true;
                    });
                    
                    $("tr:odd", tab).css('background-color', '#F5F5F5');
                    $("tr:even", tab).css('background-color', '#EEEEEE');
                    $("#UpdatePanel").html(tab);
                    if (tablerow == false) {
                        $("#UpdatePanel").hide();
                        if(deptId!=0)
                        $("#messageLabel").text("No Courses are Available in this Department.");
                    }
                    
                },
            });
            return false;
        });
    });
</script>

UnversityManagementSystem/Views/RoomAllocation/UnallocateRoom.cshtml
@model UnversityManagementSystem.Models.RoomAllocation




<h2>Unassign Courses</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group" style="text-align: center">
    <input type="button" value="Unallocate All Rooms" id="UnallocateRooms" class="btn btn-lg" />
    </div>
}
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script>
    $(document).ready(function () {
        $("#UnallocateRooms").click(function () {

            var r = confirm("Are you sure to unallocate all classrooms info?");
            if (r == true) {

                var jsnFormatData = { name: r};
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("UnallocateAllRooms", "RoomAllocation")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsnFormatData),
                    dataType: "json",
                    success: function (data) {

                        if (data == true) {
                            alert("All rooms unallocated successffully!");
                        } else {
                            alert("No rooms are available to unallocate");
                        }
                    },
                });

            }
            return false;

        });
    });

</script>